{{- if .Values.serviceAccounts.capiManager.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster-api-core.managerServiceAccountName" . }}
  labels:
    cluster.x-k8s.io/provider: cluster-api
  {{- include "cluster-api-core.labels" . | nindent 4 }}
  {{- with .Values.serviceAccounts.capiManager.labels }}
  {{ toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with .Values.serviceAccounts.capiManager.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}