apiVersion: clusterctl.cluster.x-k8s.io/v1alpha3
kind: Provider
metadata:
  labels:
    cluster.x-k8s.io/provider: cluster-api
    clusterctl.cluster.x-k8s.io: ''
    clusterctl.cluster.x-k8s.io/core: inventory
  name: cluster-api
providerName: cluster-api
type: CoreProvider
version: {{ .Values.controllerManager.manager.image.tag | default .Chart.AppVersion }}
