asoControllerManager:
  annotations: {}
  kubeRbacProxy:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    image:
      repository: gcr.io/kubebuilder/kube-rbac-proxy
      tag: v0.13.1
    resources:
      limits: {}
      requests: {}
  labels: {}
  manager:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    image:
      repository: mcr.microsoft.com/k8s/azureserviceoperator
      tag: v2.5.0
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
  nodeSelector:
    kubernetes.io/os: linux
  replicas: 1
asoControllerManagerMetricsService:
  ports:
    - name: metrics
      port: 8080
      targetPort: 0
  type: ClusterIP
asoControllerSettings:
  azureAuthorityHost: ""
  azureClientId: ""
  azureResourceManagerAudience: ""
  azureResourceManagerEndpoint: ""
  azureSubscriptionId: ""
  azureSyncPeriod: ""
  azureTenantId: ""
  azureClientSecret: ""
asoProxyService:
  ports:
    - name: https
      port: 8443
      targetPort: https
  type: ClusterIP
asoWebhookService:
  ports:
    - port: 443
      targetPort: 9443
  type: ClusterIP
capzControllerManager:
  annotations: {}
  labels: {}
  manager:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      runAsGroup: 65532
      runAsUser: 65532
    image:
      repository: registry.k8s.io/cluster-api-azure/cluster-api-azure-controller
      tag: v1.14.0
    imagePullPolicy: IfNotPresent
    resources:
      limits: {}
      requests: {}
  nodeSelector: {}
  replicas: 1
capzWebhookService:
  ports:
    - port: 443
      targetPort: webhook-server
  type: ClusterIP
configVariables:
  additionalAsoCrds: ' '
  azureAuthorityHost: '""'
  azureResourceManagerAudience: '""'
  azureResourceManagerEndpoint: '""'
  azureSyncPeriod: '""'
  capzDiagnosticsAddress: :8443
  capzInsecureDiagnostics: false
  exprimental:
    aksResourceHealth: false
    edgezone: false
    machinePool: false
crds:
  create: true
imagePullSecrets: []
kubernetesClusterDomain: cluster.local
serviceAccounts:
  asoDefault:
    annotations: {}
    create: true
    labels: {}
    name: ""
  capzManager:
    annotations: {}
    create: true
    labels: {}
    name: ""
nameOverride: capz
fullnameOverride: ""
bootstrapMode: true
