configVariables:
  capiDiagnosticsAddress: :8443
  capiInsecureDiagnostics: false
  clusterTopology: false
  exprimental:
    clusterResourceSet: false
    machinePool: false
    machineSetPreflightChecks: false
    runtimeSdk: false
controllerManager:
  annotations: {}
  labels: {}
  manager:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      privileged: false
      runAsGroup: 65532
      runAsUser: 65532
    image:
      repository: registry.k8s.io/cluster-api/cluster-api-controller
      tag: v1.6.0
    imagePullPolicy: IfNotPresent
    resources:
      limits: {}
      requests: {}
  nodeSelector: {}
  replicas: 1
crds:
  create: true
imagePullSecrets: []
kubernetesClusterDomain: cluster.local
serviceAccounts:
  manager:
    annotations: {}
    create: true
    labels: {}
    name: ""
webhookService:
  ports:
    - port: 443
      targetPort: webhook-server
  type: ClusterIP
nameOverride: ""
fullnameOverride: ""
