apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "cluster-api-provider-aws.fullname" . }}-serving-cert
  labels:
  {{- include "cluster-api-provider-aws.labels" . | nindent 4 }}
spec:
  dnsNames:
  - '{{ include "cluster-api-provider-aws.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc'
  - '{{ include "cluster-api-provider-aws.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.{{ .Values.kubernetesClusterDomain }}'
  issuerRef:
    kind: Issuer
    name: '{{ include "cluster-api-provider-aws.fullname" . }}-selfsigned-issuer'
  secretName: capa-webhook-service-cert