apiVersion: v1
kind: Service
metadata:
  name: {{ include "cluster-api-provider-aws.fullname" . }}-webhook-service
  labels:
    cluster.x-k8s.io/provider: infrastructure-aws
  {{- include "cluster-api-provider-aws.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    cluster.x-k8s.io/provider: infrastructure-aws
  {{- include "cluster-api-provider-aws.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.webhookService.ports | toYaml | nindent 2 -}}