configVariables:
  capgLoglevel: 0
  exprimental:
    capgGke: false
controllerManager:
  annotations: {}
  labels: {}
  manager:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      privileged: false
      runAsGroup: 65532
      runAsUser: 65532
    env:
      googleApplicationCredentials: /home/.gcp/credentials.json
    image:
      repository: registry.k8s.io/cluster-api-gcp/cluster-api-gcp-controller
      tag: v1.4.0
    imagePullPolicy: IfNotPresent
    resources:
      limits: {}
      requests: {}
  nodeSelector: {}
  replicas: 1
crds:
  create: true
imagePullSecrets: []
kubernetesClusterDomain: cluster.local
managerBootstrapCredentials:
  credentialsJson: ""
serviceAccounts:
  manager:
    annotations: {}
    create: true
    labels: {}
    name: ""
webhookService:
  ports:
    - port: 443
      targetPort: webhook-server
  type: ClusterIP
bootstrapMode: true
