apiVersion: v1
kind: Service
metadata:
  name: {{ include "cluster-api-provider-azure.fullname" . }}-aso-controller-manager-metrics-service
  labels:
    control-plane: controller-manager
  {{- include "cluster-api-provider-azure.labels" . | nindent 4 }}
spec:
  type: {{ .Values.asoControllerManagerMetricsService.type }}
  selector:
    control-plane: controller-manager
  {{- include "cluster-api-provider-azure.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.asoControllerManagerMetricsService.ports | toYaml | nindent 2 -}}