apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cluster-api-provider-azure.fullname" . }}-aso-crd-manager-role
  labels:
  {{- include "cluster-api-provider-azure.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cluster-api-provider-azure.fullname" . }}-aso-crd-manager-rolebinding
  labels:
  {{- include "cluster-api-provider-azure.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "cluster-api-provider-azure.fullname" . }}-aso-crd-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "cluster-api-provider-azure.asoDefaultServiceAccountName" . }}'
  namespace: '{{ .Release.Namespace }}'