apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster-api-provider-azure.fullname" . }}-aso-controller-settings
  labels:
  {{- include "cluster-api-provider-azure.labels" . | nindent 4 }}
data:
{{- include "cluster-api-provider-azure.aso-credentials" . | nindent 2 }}
type: Opaque
