apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cluster-api-provider-azure.fullname" . }}-azureserviceoperator-proxy-role
  labels:
  {{- include "cluster-api-provider-azure.labels" . | nindent 4 }}
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cluster-api-provider-azure.fullname" . }}-azureserviceoperator-proxy-rolebinding
  labels:
  {{- include "cluster-api-provider-azure.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "cluster-api-provider-azure.fullname" . }}-azureserviceoperator-proxy-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "cluster-api-provider-azure.serviceAccountName" . }}'
  namespace: '{{ .Release.Namespace }}'