apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "cluster-api-provider-azure.fullname" . }}-capz-serving-cert
  labels:
  {{- include "cluster-api-provider-azure.labels" . | nindent 4 }}
spec:
  dnsNames:
  - '{{ include "cluster-api-provider-azure.fullname" . }}-capz-webhook-service.{{ .Release.Namespace }}.svc'
  - '{{ include "cluster-api-provider-azure.fullname" . }}-capz-webhook-service.{{ .Release.Namespace }}.svc.{{ .Values.kubernetesClusterDomain }}'
  issuerRef:
    kind: Issuer
    name: '{{ include "cluster-api-provider-azure.fullname" . }}-capz-selfsigned-issuer'
  secretName: capz-webhook-service-cert