apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "cluster-api-provider-azure.fullname" . }}-capz-selfsigned-issuer
  labels:
  {{- include "cluster-api-provider-azure.labels" . | nindent 4 }}
spec:
  selfSigned: {}