apiVersion: clusterctl.cluster.x-k8s.io/v1alpha3
kind: Provider
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-azure
    clusterctl.cluster.x-k8s.io: ''
    clusterctl.cluster.x-k8s.io/core: inventory
  name: infrastructure-azure
providerName: azure
type: InfrastructureProvider
version: {{ .Values.controllerManager.manager.image.tag | default .Chart.AppVersion }}
