{{- if .Values.serviceAccounts.manager.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster-api-provider-docker.managerServiceAccountName" . }}
  labels:
    cluster.x-k8s.io/provider: infrastructure-docker
  {{- include "cluster-api-provider-docker.labels" . | nindent 4 }}
  {{- with .Values.serviceAccounts.manager.labels }}
  {{ toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with .Values.serviceAccounts.manager.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}