apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "cluster-api-provider-docker.fullname" . }}-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "cluster-api-provider-docker.fullname" . }}-serving-cert
  labels:
  {{- include "cluster-api-provider-docker.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: '{{ include "cluster-api-provider-docker.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-dockercluster
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.dockercluster.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dockerclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: '{{ include "cluster-api-provider-docker.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-dockerclustertemplate
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.dockerclustertemplate.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dockerclustertemplates
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: '{{ include "cluster-api-provider-docker.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-dockermachinetemplate
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.dockermachinetemplate.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dockermachinetemplates
  sideEffects: None