{{- if .Values.serviceAccounts.capgManager.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster-api-provider-gcp.managerServiceAccountName" . }}
  labels:
    cluster.x-k8s.io/provider: infrastructure-gcp
  {{- include "cluster-api-provider-gcp.labels" . | nindent 4 }}
  {{- with .Values.serviceAccounts.capgManager.labels }}
  {{ toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with .Values.serviceAccounts.capgManager.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}