{{- if .Values.serviceAccounts.capiKubeadmControlPlaneManager.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster-api-control-plane.managerServiceAccountName" . }}
  labels:
    cluster.x-k8s.io/provider: control-plane-kubeadm
  {{- include "cluster-api-control-plane.labels" . | nindent 4 }}
  {{- with .Values.serviceAccounts.capiKubeadmControlPlaneManager.labels }}
  {{ toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with .Values.serviceAccounts.capiKubeadmControlPlaneManager.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}