apiVersion: clusterctl.cluster.x-k8s.io/v1alpha3
kind: Provider
metadata:
  labels:
    cluster.x-k8s.io/provider: control-plane-kubeadm
    clusterctl.cluster.x-k8s.io: ''
    clusterctl.cluster.x-k8s.io/core: inventory
  name: control-plane-kubeadm
providerName: kubeadm
type: ControlPlaneProvider
version: {{ .Values.controllerManager.manager.image.tag | default .Chart.AppVersion }}
