apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "cluster-api-control-plane.fullname" . }}-serving-cert
  labels:
  {{- include "cluster-api-control-plane.labels" . | nindent 4 }}
spec:
  dnsNames:
  - '{{ include "cluster-api-control-plane.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc'
  - '{{ include "cluster-api-control-plane.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.{{ .Values.kubernetesClusterDomain }}'
  issuerRef:
    kind: Issuer
    name: '{{ include "cluster-api-control-plane.fullname" . }}-selfsigned-issuer'
  secretName: capi-kubeadm-control-plane-webhook-service-cert
  subject:
    organizations:
    - k8s-sig-cluster-lifecycle